CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  upc VARCHAR(12) NOT NULL UNIQUE,
  price DECIMAL(10, 2) NOT NULL,
  has_image BOOLEAN NOT NULL DEFAULT FALSE
);