services:
  proxy:
    image: traefik:v3.1
    command: --providers.docker --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  ############## DATABASE AND VISUALIZER ##############
  postgres:
    image: postgres:17.1
    ports:
      - "5432:5432"
    volumes:
      - ./dev/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog

  ######## DATABASE VISUALIZER ##########
  # The natively-running app will connect to this using the endpoint 
  # http://db.localhost
  #######################################
  pgadmin:
    image: dpage/pgadmin4:8.13.0
    volumes:
      - ./dev/pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mycomp.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - postgres
    labels:
      traefik.http.routers.pgadmin.rule: Host(`db.localhost`)
      traefik.http.services.pgadmin.loadbalancer.server.port: 80

  ############## LOCAL AWS ##############
  # The natively-running app will connect to this using the endpoint 
  # http://aws.localhost
  #######################################
  aws:
    image: localstack/localstack:3.8.1
    labels:
      traefik.http.routers.aws.rule: Host(`aws.localhost`)
      traefik.http.services.aws.loadbalancer.server.port: 4566

  bucket-creator:
    image: localstack/localstack:3.8.1
    entrypoint: []
    command: awslocal --endpoint-url http://aws:4566 s3api create-bucket --bucket product-images
    depends_on:
      aws:
        condition: service_healthy

  ############## MOCK INVENTORY SERVICE ##############
  # The natively-running app will connect to this using the endpoint 
  # http://inventory.localhost
  #######################################
  mock-inventory:
    image: wiremock/wiremock:3.9.2
    volumes:
      - ./dev/inventory-mocks:/home/wiremock
    labels:
      traefik.http.routers.mock-inventory.rule: Host(`inventory.localhost`)
      traefik.http.services.mock-inventory.loadbalancer.server.port: 8080

  ############## KAFKA AND VISUALIZATION ##############
  kafka:
    image: apache/kafka-native:3.9.0
    ports:
      - 9092:9092
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-topic-creator:
    image: apache/kafka:3.9.0
    command: /opt/kafka/bin/kafka-topics.sh --create --topic products --partitions 1 --replication-factor 1 --bootstrap-server kafka:9093
    depends_on:
      - kafka

  ############## KAFKA UI ##############
  # The natively-running app will connect to this using the endpoint 
  # http://kafka.localhost
  #######################################
  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:01aa8ab36387c5f1d66d098e71488bfb0eb5f39c
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka
    labels:
      traefik.http.routers.kafka-ui.rule: Host(`kafka.localhost`)
      traefik.http.services.kafka-ui.loadbalancer.server.port: 8080
